"use client";

import { useState, useEffect, useRef } from "react";
import { Sparkles, Save, Edit3, X } from "lucide-react";
import { updateProfileStory, refineStoryWithAI } from "@/lib/actions";

interface EditableStoryProps {
    slug: string;
    initialStory: string;
    initialPitch: string;
    isPlaceholder?: boolean;
    context?: {
        name?: string;
        bio?: string;
        niche?: string;
        metrics?: any[];
        videos?: any[];
    };
}

export function EditableStory({ slug, initialStory, initialPitch, isPlaceholder = false, context }: EditableStoryProps) {
    const [isEditing, setIsEditing] = useState(false);
    const [story, setStory] = useState(initialStory);
    const [pitch, setPitch] = useState(initialPitch);
    const [isSaving, setIsSaving] = useState(false);
    const [isRefining, setIsRefining] = useState(false);
    const hasAutoGenerated = useRef(false);

    useEffect(() => {
        const autoGenerate = async () => {
            if (isPlaceholder && !hasAutoGenerated.current) {
                console.log("⚡ Auto-generating AI Story for new profile...");
                hasAutoGenerated.current = true;
                setIsRefining(true);

                try {
                    // 1. Generate Content
                    const refined = await refineStoryWithAI(story, pitch, context);

                    if (refined && refined.story && refined.pitch) {
                        setStory(refined.story);
                        setPitch(refined.pitch);

                        // 2. Save immediately
                        console.log("💾 Auto-saving generated story...");
                        setIsSaving(true);
                        await updateProfileStory(slug, refined.story, refined.pitch);
                        console.log("✅ Auto-save complete.");
                    }
                } catch (error) {
                    console.error("❌ Auto-generation failed:", error);
                } finally {
                    setIsRefining(false);
                    setIsSaving(false);
                }
            }
        };

        autoGenerate();
    }, [isPlaceholder, slug, context]); // Removed story/pitch dependencies to avoid loops

    const handleSave = async () => {
        setIsSaving(true);
        try {
            await updateProfileStory(slug, story, pitch);
            setIsEditing(false);
        } catch (error) {
            console.error(error);
            alert("Erro ao salvar alterações.");
        } finally {
            setIsSaving(false);
        }
    };

    const handleAIEnhance = async () => {
        setIsRefining(true);
        try {
            const refined = await refineStoryWithAI(story, pitch, context);
            if (refined) {
                setStory(refined.story);
                setPitch(refined.pitch);
            }
        } catch (error) {
            console.error(error);
            alert("Erro ao refinar com IA.");
        } finally {
            setIsRefining(false);
        }
    };

    if (!isEditing) {
        return (
            <div className="group relative" style={{ position: "relative" }}>
                <button
                    onClick={() => setIsEditing(true)}
                    style={{
                        position: "absolute",
                        top: "-3rem",
                        right: "0",
                        padding: "0.75rem",
                        background: "rgba(255, 255, 255, 0.05)",
                        border: "1px solid rgba(255, 255, 255, 0.1)",
                        borderRadius: "50%",
                        cursor: "pointer",
                        transition: "all 0.2s ease",
                        color: "var(--muted-foreground)",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center"
                    }}
                    className="hover-trigger no-print"
                    title="Editar Minha História"
                >
                    <Edit3 size={18} />
                </button>

                {isRefining ? (
                    <div style={{ padding: "4rem", textAlign: "center", color: "var(--muted-foreground)" }}>
                        <Sparkles className="animate-spin" style={{ margin: "0 auto 1rem", opacity: 0.5 }} size={32} />
                        <p>A IA está a escrever a tua história estratégica...</p>
                    </div>
                ) : (
                    <>
                        <div
                            style={{
                                color: "var(--foreground)",
                                fontSize: "1.25rem",
                                lineHeight: "1.9",
                                marginBottom: "3rem",
                                opacity: 0.9,
                                fontWeight: 400
                            }}
                        >
                            {story.split("\n").filter(line => line.trim()).map((line, i) => (
                                <p key={i} style={{ marginBottom: "1.5rem" }} dangerouslySetInnerHTML={{ __html: line.replace(/\*\*(.*?)\*\*/g, '<strong style="color: var(--primary); font-weight: 700;">$1</strong>') }} />
                            ))}
                        </div>

                        <div
                            style={{
                                marginTop: "2rem",
                                padding: "1.5rem 0",
                                borderTop: "1px solid var(--border)",
                                borderBottom: "1px solid var(--border)"
                            }}
                        >
                            <h4 style={{
                                marginBottom: "1.5rem",
                                fontSize: "1.5rem",
                                fontWeight: 700,
                                color: "var(--foreground)",
                                display: "flex",
                                alignItems: "center",
                                gap: "0.75rem",
                                letterSpacing: "-0.02em"
                            }}>
                                <span style={{ width: "24px", height: "3px", background: "var(--primary)", borderRadius: "2px" }}></span>
                                Por que investir nesta parceria?
                            </h4>
                            <div style={{ color: "var(--muted-foreground)", fontSize: "1.1rem", lineHeight: "1.8" }}>
                                {pitch.split("\n").filter(line => line.trim()).map((line, i) => {
                                    const isListItem = line.trim().match(/^\d\./);
                                    return (
                                        <p key={i} style={{
                                            marginBottom: "1rem",
                                            paddingLeft: isListItem ? "1.5rem" : "0",
                                            // borderLeft: isListItem ? "2px solid rgba(74, 74, 74, 0.3)" : "none" 
                                        }} dangerouslySetInnerHTML={{ __html: line.replace(/\*\*(.*?)\*\*/g, '<strong style="color: var(--foreground); font-weight: 600;">$1</strong>') }} />
                                    );
                                })}
                            </div>
                        </div>
                    </>
                )}
            </div>
        );
    }

    return (
        <div style={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
            {/* Print-only version of the content */}
            <div className="print-story-content" style={{ display: "none" }}>
                <div style={{ marginBottom: "2rem" }}>
                    <h4 style={{ fontSize: "1.5rem", fontWeight: "bold", marginBottom: "1rem", color: "#000" }}>Minha História</h4>
                    <div style={{ whiteSpace: "pre-wrap" }}>{story}</div>
                </div>
                <div>
                    <h4 style={{ fontSize: "1.5rem", fontWeight: "bold", marginBottom: "1rem", color: "#000" }}>Pitch de Investimento</h4>
                    <div style={{ whiteSpace: "pre-wrap" }}>{pitch}</div>
                </div>
            </div>

            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }} className="no-print">
                <button
                    onClick={handleAIEnhance}
                    disabled={isRefining}
                    className="no-print"
                    style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "0.75rem",
                        padding: "0.75rem 1.25rem",
                        background: "var(--secondary)",
                        border: "1px solid var(--border)",
                        color: "var(--primary)",
                        borderRadius: "1rem",
                        cursor: isRefining ? "not-allowed" : "pointer",
                        fontWeight: 600,
                        fontSize: "0.875rem",
                        transition: "all 0.2s",
                        opacity: isRefining ? 0.7 : 1
                    }}
                >
                    <Sparkles size={16} className={isRefining ? "animate-spin" : ""} />
                    {isRefining ? "Refinando..." : "Incrementar com IA"}
                </button>
                <div style={{ display: "flex", gap: "1rem" }}>
                    <button
                        onClick={() => setIsEditing(false)}
                        style={{
                            padding: "0.75rem",
                            background: "transparent",
                            border: "none",
                            color: "var(--muted-foreground)",
                            cursor: "pointer"
                        }}
                    >
                        <X size={20} />
                    </button>
                    <button
                        onClick={handleSave}
                        disabled={isSaving}
                        style={{
                            display: "flex",
                            alignItems: "center",
                            gap: "0.75rem",
                            padding: "0.75rem 1.75rem",
                            background: "var(--primary)",
                            color: "white",
                            border: "none",
                            borderRadius: "1rem",
                            cursor: isSaving ? "not-allowed" : "pointer",
                            fontWeight: 700,
                            boxShadow: "0 10px 20px -5px rgba(67, 97, 238, 0.4)"
                        }}
                    >
                        {isSaving ? "Salvando..." : <><Save size={16} /> Salvar Alterações</>}
                    </button>
                </div>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }} className="no-print">
                <div>
                    <label style={{ display: "block", fontSize: "0.75rem", fontWeight: 700, textTransform: "uppercase", color: "var(--muted-foreground)", letterSpacing: "0.1em", marginBottom: "0.75rem" }}>
                        Minha História
                    </label>
                    <textarea
                        value={story}
                        onChange={(e) => setStory(e.target.value)}
                        style={{
                            width: "100%",
                            height: "20rem",
                            background: "var(--secondary)",
                            border: "1px solid var(--border)",
                            borderRadius: "1.5rem",
                            padding: "1.5rem",
                            color: "var(--foreground)",
                            fontSize: "1.1rem",
                            lineHeight: "1.6",
                            resize: "none",
                            outline: "none",
                            fontFamily: "inherit"
                        }}
                    />
                </div>

                <div>
                    <label style={{ display: "block", fontSize: "0.75rem", fontWeight: 700, textTransform: "uppercase", color: "var(--muted-foreground)", letterSpacing: "0.1em", marginBottom: "0.75rem" }}>
                        Pitch de Investimento
                    </label>
                    <textarea
                        value={pitch}
                        onChange={(e) => setPitch(e.target.value)}
                        style={{
                            width: "100%",
                            height: "12rem",
                            background: "var(--secondary)",
                            border: "1px solid var(--border)",
                            borderRadius: "1.5rem",
                            padding: "1.5rem",
                            color: "var(--foreground)",
                            fontSize: "1.1rem",
                            lineHeight: "1.6",
                            resize: "none",
                            outline: "none",
                            fontFamily: "inherit"
                        }}
                    />
                </div>
            </div>
        </div>
    );
}
