"use client";

import { useState, useEffect, useRef } from "react";
import { Sparkles, Save, Edit3, X, Loader2 } from "lucide-react";
import { updateProfileStory, refineStoryWithAI } from "@/lib/actions";

interface EditableStoryProps {
    slug: string;
    initialStory: string;
    initialPitch: string;
    isPlaceholder?: boolean;
    context?: {
        name?: string;
        bio?: string;
        niche?: string;
        metrics?: any[];
        videos?: any[];
    };
}

export function EditableStory({ 
    slug, 
    initialStory, 
    initialPitch, 
    isPlaceholder = false, 
    context 
}: EditableStoryProps) {
    const [isEditing, setIsEditing] = useState(false);
    const [story, setStory] = useState(initialStory);
    const [pitch, setPitch] = useState(initialPitch);
    const [isSaving, setIsSaving] = useState(false);
    const [isRefining, setIsRefining] = useState(false);
    const hasAutoGenerated = useRef(false);

    useEffect(() => {
        const autoGenerate = async () => {
            if (isPlaceholder && !hasAutoGenerated.current) {
                console.log("⚡ Auto-generating AI Story for new profile...");
                hasAutoGenerated.current = true;
                setIsRefining(true);

                try {
                    const refined = await refineStoryWithAI(story, pitch, context);

                    if (refined && refined.story && refined.pitch) {
                        setStory(refined.story);
                        setPitch(refined.pitch);

                        console.log("💾 Auto-saving generated story...");
                        setIsSaving(true);
                        await updateProfileStory(slug, refined.story, refined.pitch);
                        console.log("✅ Auto-save complete.");
                    }
                } catch (error) {
                    console.error("❌ Auto-generation failed:", error);
                } finally {
                    setIsRefining(false);
                    setIsSaving(false);
                }
            }
        };

        autoGenerate();
    }, [isPlaceholder, slug, context]);

    const handleSave = async () => {
        setIsSaving(true);
        try {
            await updateProfileStory(slug, story, pitch);
            setIsEditing(false);
        } catch (error) {
            console.error(error);
            alert("Erro ao salvar alterações.");
        } finally {
            setIsSaving(false);
        }
    };

    const handleAIEnhance = async () => {
        setIsRefining(true);
        try {
            const refined = await refineStoryWithAI(story, pitch, context);
            if (refined) {
                setStory(refined.story);
                setPitch(refined.pitch);
            }
        } catch (error) {
            console.error(error);
            alert("Erro ao refinar com IA.");
        } finally {
            setIsRefining(false);
        }
    };

    if (!isEditing) {
        return (
            <div style={{ position: "relative" }}>
                {/* Edit Button */}
                <button
                    onClick={() => setIsEditing(true)}
                    style={{
                        position: "absolute",
                        top: "-2.5rem",
                        right: "0",
                        padding: "var(--space-3)",
                        background: "var(--secondary)",
                        border: "1px solid var(--border)",
                        borderRadius: "var(--radius-full)",
                        cursor: "pointer",
                        transition: "all var(--transition-base)",
                        color: "var(--muted-foreground)",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                    }}
                    className="no-print"
                    title="Editar Minha História"
                    onMouseEnter={(e) => {
                        e.currentTarget.style.borderColor = "var(--primary)";
                        e.currentTarget.style.color = "var(--primary)";
                    }}
                    onMouseLeave={(e) => {
                        e.currentTarget.style.borderColor = "var(--border)";
                        e.currentTarget.style.color = "var(--muted-foreground)";
                    }}
                >
                    <Edit3 size={16} />
                </button>

                {isRefining ? (
                    <div style={{ 
                        padding: "var(--space-12)", 
                        textAlign: "center", 
                        color: "var(--muted-foreground)",
                    }}>
                        <Loader2 
                            size={32} 
                            style={{ 
                                margin: "0 auto var(--space-4)", 
                                opacity: 0.5,
                                animation: "spin 1s linear infinite",
                            }} 
                        />
                        <p style={{ fontSize: "var(--text-sm)" }}>
                            A IA está escrevendo sua história estratégica...
                        </p>
                    </div>
                ) : (
                    <>
                        {/* Story Content */}
                        <div
                            style={{
                                color: "var(--foreground)",
                                fontSize: "var(--text-lg)",
                                lineHeight: "var(--leading-relaxed)",
                                marginBottom: "var(--space-8)",
                            }}
                        >
                            {story.split("\n").filter(line => line.trim()).map((line, i) => (
                                <p 
                                    key={i} 
                                    style={{ marginBottom: "var(--space-4)" }} 
                                    dangerouslySetInnerHTML={{ 
                                        __html: line.replace(
                                            /\*\*(.*?)\*\*/g, 
                                            '<strong style="color: var(--primary); font-weight: 600;">$1</strong>'
                                        ) 
                                    }} 
                                />
                            ))}
                        </div>

                        {/* Pitch Section */}
                        <div
                            style={{
                                marginTop: "var(--space-6)",
                                padding: "var(--space-6) 0",
                                borderTop: "1px solid var(--border)",
                            }}
                        >
                            <h4 style={{
                                marginBottom: "var(--space-6)",
                                fontSize: "var(--text-xl)",
                                fontWeight: 600,
                                color: "var(--foreground)",
                                display: "flex",
                                alignItems: "center",
                                gap: "var(--space-3)",
                            }}>
                                <span style={{ 
                                    width: "20px", 
                                    height: "3px", 
                                    background: "var(--primary)", 
                                    borderRadius: "var(--radius-full)",
                                }} />
                                Por que investir nesta parceria?
                            </h4>
                            <div style={{ 
                                color: "var(--muted-foreground)", 
                                fontSize: "var(--text-base)", 
                                lineHeight: "var(--leading-relaxed)",
                            }}>
                                {pitch.split("\n").filter(line => line.trim()).map((line, i) => {
                                    const isListItem = line.trim().match(/^\d\./);
                                    return (
                                        <p 
                                            key={i} 
                                            style={{
                                                marginBottom: "var(--space-3)",
                                                paddingLeft: isListItem ? "var(--space-4)" : "0",
                                            }} 
                                            dangerouslySetInnerHTML={{ 
                                                __html: line.replace(
                                                    /\*\*(.*?)\*\*/g, 
                                                    '<strong style="color: var(--foreground); font-weight: 600;">$1</strong>'
                                                ) 
                                            }} 
                                        />
                                    );
                                })}
                            </div>
                        </div>
                    </>
                )}
            </div>
        );
    }

    // Editing Mode
    return (
        <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-6)" }}>
            {/* Print-only version */}
            <div className="print-story-content" style={{ display: "none" }}>
                <div style={{ marginBottom: "var(--space-6)" }}>
                    <h4 style={{ 
                        fontSize: "var(--text-xl)", 
                        fontWeight: 600, 
                        marginBottom: "var(--space-4)", 
                        color: "#000",
                    }}>
                        Minha História
                    </h4>
                    <div style={{ whiteSpace: "pre-wrap" }}>{story}</div>
                </div>
                <div>
                    <h4 style={{ 
                        fontSize: "var(--text-xl)", 
                        fontWeight: 600, 
                        marginBottom: "var(--space-4)", 
                        color: "#000",
                    }}>
                        Pitch de Investimento
                    </h4>
                    <div style={{ whiteSpace: "pre-wrap" }}>{pitch}</div>
                </div>
            </div>

            {/* Toolbar */}
            <div 
                style={{ 
                    display: "flex", 
                    alignItems: "center", 
                    justifyContent: "space-between",
                    flexWrap: "wrap",
                    gap: "var(--space-4)",
                }} 
                className="no-print"
            >
                <button
                    onClick={handleAIEnhance}
                    disabled={isRefining}
                    style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "var(--space-2)",
                        padding: "var(--space-3) var(--space-4)",
                        background: "var(--primary-light)",
                        border: "1px solid transparent",
                        color: "var(--primary)",
                        borderRadius: "var(--radius-md)",
                        cursor: isRefining ? "not-allowed" : "pointer",
                        fontWeight: 600,
                        fontSize: "var(--text-sm)",
                        transition: "all var(--transition-base)",
                        opacity: isRefining ? 0.7 : 1,
                    }}
                    onMouseEnter={(e) => {
                        if (!isRefining) {
                            e.currentTarget.style.background = "var(--primary)";
                            e.currentTarget.style.color = "white";
                        }
                    }}
                    onMouseLeave={(e) => {
                        e.currentTarget.style.background = "var(--primary-light)";
                        e.currentTarget.style.color = "var(--primary)";
                    }}
                >
                    <Sparkles 
                        size={16} 
                        style={{ 
                            animation: isRefining ? "spin 1s linear infinite" : "none" 
                        }} 
                    />
                    {isRefining ? "Refinando..." : "Incrementar com IA"}
                </button>
                
                <div style={{ display: "flex", gap: "var(--space-3)" }}>
                    <button
                        onClick={() => setIsEditing(false)}
                        style={{
                            padding: "var(--space-3)",
                            background: "transparent",
                            border: "none",
                            color: "var(--muted-foreground)",
                            cursor: "pointer",
                            borderRadius: "var(--radius-md)",
                            transition: "all var(--transition-base)",
                        }}
                        onMouseEnter={(e) => {
                            e.currentTarget.style.background = "var(--secondary)";
                        }}
                        onMouseLeave={(e) => {
                            e.currentTarget.style.background = "transparent";
                        }}
                    >
                        <X size={20} />
                    </button>
                    <button
                        onClick={handleSave}
                        disabled={isSaving}
                        style={{
                            display: "flex",
                            alignItems: "center",
                            gap: "var(--space-2)",
                            padding: "var(--space-3) var(--space-5)",
                            background: "var(--primary)",
                            color: "white",
                            border: "none",
                            borderRadius: "var(--radius-md)",
                            cursor: isSaving ? "not-allowed" : "pointer",
                            fontWeight: 600,
                            fontSize: "var(--text-sm)",
                            boxShadow: "var(--shadow-primary)",
                            transition: "all var(--transition-base)",
                        }}
                        onMouseEnter={(e) => {
                            if (!isSaving) {
                                e.currentTarget.style.transform = "translateY(-1px)";
                                e.currentTarget.style.boxShadow = "var(--shadow-primary-lg)";
                            }
                        }}
                        onMouseLeave={(e) => {
                            e.currentTarget.style.transform = "translateY(0)";
                            e.currentTarget.style.boxShadow = "var(--shadow-primary)";
                        }}
                    >
                        {isSaving ? (
                            <>
                                <Loader2 size={16} style={{ animation: "spin 1s linear infinite" }} />
                                Salvando...
                            </>
                        ) : (
                            <>
                                <Save size={16} /> Salvar
                            </>
                        )}
                    </button>
                </div>
            </div>

            {/* Text Areas */}
            <div 
                style={{ 
                    display: "flex", 
                    flexDirection: "column", 
                    gap: "var(--space-5)" 
                }} 
                className="no-print"
            >
                <div>
                    <label style={{ 
                        display: "block", 
                        fontSize: "var(--text-xs)", 
                        fontWeight: 600, 
                        textTransform: "uppercase", 
                        color: "var(--muted-foreground)", 
                        letterSpacing: "0.08em", 
                        marginBottom: "var(--space-3)",
                    }}>
                        Minha História
                    </label>
                    <textarea
                        value={story}
                        onChange={(e) => setStory(e.target.value)}
                        style={{
                            width: "100%",
                            height: "18rem",
                            background: "var(--secondary)",
                            border: "1px solid var(--border)",
                            borderRadius: "var(--radius-lg)",
                            padding: "var(--space-5)",
                            color: "var(--foreground)",
                            fontSize: "var(--text-base)",
                            lineHeight: "var(--leading-relaxed)",
                            resize: "none",
                            outline: "none",
                            fontFamily: "inherit",
                            transition: "border-color var(--transition-base)",
                        }}
                        onFocus={(e) => {
                            e.currentTarget.style.borderColor = "var(--primary)";
                        }}
                        onBlur={(e) => {
                            e.currentTarget.style.borderColor = "var(--border)";
                        }}
                    />
                </div>

                <div>
                    <label style={{ 
                        display: "block", 
                        fontSize: "var(--text-xs)", 
                        fontWeight: 600, 
                        textTransform: "uppercase", 
                        color: "var(--muted-foreground)", 
                        letterSpacing: "0.08em", 
                        marginBottom: "var(--space-3)",
                    }}>
                        Pitch de Investimento
                    </label>
                    <textarea
                        value={pitch}
                        onChange={(e) => setPitch(e.target.value)}
                        style={{
                            width: "100%",
                            height: "12rem",
                            background: "var(--secondary)",
                            border: "1px solid var(--border)",
                            borderRadius: "var(--radius-lg)",
                            padding: "var(--space-5)",
                            color: "var(--foreground)",
                            fontSize: "var(--text-base)",
                            lineHeight: "var(--leading-relaxed)",
                            resize: "none",
                            outline: "none",
                            fontFamily: "inherit",
                            transition: "border-color var(--transition-base)",
                        }}
                        onFocus={(e) => {
                            e.currentTarget.style.borderColor = "var(--primary)";
                        }}
                        onBlur={(e) => {
                            e.currentTarget.style.borderColor = "var(--border)";
                        }}
                    />
                </div>
            </div>
        </div>
    );
}
